Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Breadlesscode.Notification:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Breadlesscode.Notification: true
Breadlesscode:
  Notification:
    classes:
      base: 'notification'
